# APLICANDO LASSO A DATASET HOUSING

# 1 - IMPORTAMOS LIBRERIAS

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# 2 - CARGAMOS DATASET

In [2]:
df = pd.read_csv('https://archive.ics.uci.edu/ml/machine-learning-databases/housing/housing.data',header=None,sep=r'\s+')
df.columns =  ['CRIM', 'ZN', 'INDUS', 'CHAS', 'NOX', 'RM', 'AGE', 'DIS', 'RAD', 'TAX', 'PTRATIO', 'B', 'LSTAT', 'MEDV']
df.head(5)

,CRIM,ZN,INDUS,CHAS,NOX,RM,AGE,DIS,RAD,TAX,PTRATIO,B,LSTAT,MEDV
0,0.00632,18.0,2.31,0,0.538,6.575,65.2,4.0900,1,296.0,15.3,396.90,4.98,24.0
1,0.02731,0.0,7.07,0,0.469,6.421,78.9,4.9671,2,242.0,17.8,396.90,9.14,21.6
2,0.02729,0.0,7.07,0,0.469,7.185,61.1,4.9671,2,242.0,17.8,392.83,4.03,34.7
3,0.03237,0.0,2.18,0,0.458,6.998,45.8,6.0622,3,222.0,18.7,394.63,2.94,33.4
4,0.06905,0.0,2.18,0,0.458,7.147,54.2,6.0622,3,222.0,18.7,396.90,5.33,36.2

In [3]:
corr_matrix = df.corr()
corr_medv = corr_matrix[['MEDV']].sort_values(by='MEDV',ascending=False)
corr_medv

             MEDV
MEDV     1.000000
RM       0.695360
ZN       0.360445
B        0.333461
DIS      0.249929
CHAS     0.175260
AGE     -0.376955
RAD     -0.381626
CRIM    -0.388305
NOX     -0.427321
TAX     -0.468536
INDUS   -0.483725
PTRATIO -0.507787
LSTAT   -0.737663

In [4]:
cols = corr_medv.index.tolist()
cols.remove('MEDV')
cols

['RM',
 'ZN',
 'B',
 'DIS',
 'CHAS',
 'AGE',
 'RAD',
 'CRIM',
 'NOX',
 'TAX',
 'INDUS',
 'PTRATIO',
 'LSTAT']

# 3 - ENTRENAMIENTO CON LASSO

## 3.1 DEFINIMOS VARIABLE X y Y

In [5]:
X = df[cols].values
y = df['MEDV'].values.reshape(-1,1)

## 3.2 DIVIDIMOS DATASET EN TRAIN Y TEST

In [6]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.30)

## 3.3 ESTANDARIZAMOS TODAS LAS VARIABLES

In [7]:
from sklearn.preprocessing import StandardScaler
sc_x = StandardScaler()
X_train = sc_x.fit_transform(X_train)
X_test = sc_x.transform(X_test)

sc_y = StandardScaler()
y_train = sc_y.fit_transform(y_train)
y_test = sc_y.transform(y_test)

## 3.4 ENTRENAMOS EL MODELO

In [10]:
from sklearn.linear_model import Lasso
from sklearn.metrics import mean_squared_error, r2_score

lasso = Lasso(alpha=0.1)
lasso.fit(X_train,y_train)

y_pred_lasso = lasso.predict(X_test)

In [11]:
#evaluamos el modelo
mse_lasso = mean_squared_error(y_test,y_pred_lasso)
r2_lasso = r2_score(y_test,y_pred_lasso)

print(f'Lasso - Mean Squared Error (MSE): {mse_lasso:.4f}')
print(f'Lasso - R-squared (R2): {r2_lasso:.4f}')

Lasso - Mean Squared Error (MSE): 0.3288
Lasso - R-squared (R2): 0.6837