# EJEMPLO DE DATASET REAL PARA TRABAJO FINAL
## FUENTE : https://www.datosabiertos.gob.pe/dataset/valor-de-predio-seg%C3%BAn-porcentaje-comercial-de-la-municipalidad-distrital-de-jes%C3%BAs-mar%C3%ADa-%E2%80%93

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [20]:
df = pd.read_csv('/content/data_predio_comercial.csv', encoding='latin1', sep=';')
df.head(10)

,FECHA_CORTE,ANIO,COD_PRED,AREA_TERRENO,AREA_CONSTRUIDA,AREA_COMUN,PORCENTAJE_PROPIEDAD,BASE_IMPONIBLE,ESTADO_PREDIO,USO_PREDIO,CONDICION_PROPIEDAD,DEPARTAMENTO,PROVINCIA,DISTRITO,UBIGEO
0,20240920,2024,0fb77e19e041be33b1f2c3e44a5ec2d1910cb011598c7c...,0.19,7.9,0.0,100.0,"6,067.28",TERMINADO,COMERCIO,PROPIETARIO UNICO,LIMA,LIMA,JESUS MARIA,150113
1,20240920,2024,570786451db3707b18629c65e4623ace8a458298055db4...,68.48,60.04,0.0,100.0,"58,552.60",TERMINADO,COMERCIO,PROPIETARIO UNICO,LIMA,LIMA,JESUS MARIA,150113
2,20240920,2024,1cf02f83100567b7ba5aa5410c541afbfbe8a2ef58e60b...,83.7,340.25,0.0,100.0,"195,000.16",TERMINADO,COMERCIO,PROPIETARIO UNICO,LIMA,LIMA,JESUS MARIA,150113
3,20240920,2024,8a0435b2fdb4a58a5696ea17852bf66c2e4fbe9b19bc17...,4.35,20,0.0,100.0,"8,929.20",TERMINADO,COMERCIO,PROPIETARIO UNICO,LIMA,LIMA,JESUS MARIA,150113
4,20240920,2024,2c27b44a453cb30164af803338faa43b496a2372840bba...,23.9,59.81,0.0,100.0,"27,866.22",TERMINADO,COMERCIO,PROPIETARIO UNICO,LIMA,LIMA,JESUS MARIA,150113
5,20240920,2024,4d60c74ab33556571d0e47e8f41c0fda2329ac635ab2ed...,5.44,7.28,0.0,100.0,"8,164.87",TERMINADO,COMERCIO,PROPIETARIO UNICO,LIMA,LIMA,JESUS MARIA,150113
6,20240920,2024,9124c49e00f29bfe1936a6133fbeba59a2e3c373a8965d...,5.5,7.06,0.0,100.0,"7,277.75",TERMINADO,COMERCIO,PROPIETARIO UNICO,LIMA,LIMA,JESUS MARIA,150113
7,20240920,2024,fe70bb838b7a40e13985bfa7ea9649b98a6aeb65ed3f21...,26.56,75,0.0,100.0,"46,610.66",TERMINADO,COMERCIO,SUCESIÓN INDIVISA,LIMA,LIMA,JESUS MARIA,150113
8,20240920,2024,b7d448c68d593efd9b71480d893d1c37429ead5e7c9040...,72.3,68,0.0,100.0,"67,634.44",TERMINADO,COMERCIO,PROPIETARIO UNICO,LIMA,LIMA,JESUS MARIA,150113
9,20240920,2024,de396ed6727418261e02b0312ce9a097b5dafa98dd6d44...,32.64,72.79,0.0,100.0,"46,837.31",TERMINADO,COMERCIO,PROPIETARIO UNICO,LIMA,LIMA,JESUS MARIA,150113

# SELECCIONAMOS COLUMNAS A UTILIZAR

In [21]:
df.columns

Index(['FECHA_CORTE', 'ANIO', 'COD_PRED', 'AREA_TERRENO', 'AREA_CONSTRUIDA',
       'AREA_COMUN', 'PORCENTAJE_PROPIEDAD', 'BASE_IMPONIBLE', 'ESTADO_PREDIO',
       'USO_PREDIO', 'CONDICION_PROPIEDAD', 'DEPARTAMENTO', 'PROVINCIA',
       'DISTRITO', 'UBIGEO'],
      dtype='object')

In [22]:
data_df = df[['AREA_TERRENO', 'AREA_CONSTRUIDA',
       'AREA_COMUN', 'PORCENTAJE_PROPIEDAD', 'BASE_IMPONIBLE', 'ESTADO_PREDIO',
       'USO_PREDIO', 'CONDICION_PROPIEDAD']]

In [23]:
data_df

,AREA_TERRENO,AREA_CONSTRUIDA,AREA_COMUN,PORCENTAJE_PROPIEDAD,BASE_IMPONIBLE,ESTADO_PREDIO,USO_PREDIO,CONDICION_PROPIEDAD
0,0.19,7.9,0.0,100.0,"6,067.28",TERMINADO,COMERCIO,PROPIETARIO UNICO
1,68.48,60.04,0.0,100.0,"58,552.60",TERMINADO,COMERCIO,PROPIETARIO UNICO
2,83.7,340.25,0.0,100.0,"195,000.16",TERMINADO,COMERCIO,PROPIETARIO UNICO
3,4.35,20,0.0,100.0,"8,929.20",TERMINADO,COMERCIO,PROPIETARIO UNICO
4,23.9,59.81,0.0,100.0,"27,866.22",TERMINADO,COMERCIO,PROPIETARIO UNICO
...,...,...,...,...,...,...,...,...
10475,44.96,176.93,0.0,100.0,72990.44,TERMINADO,COMERCIO,PROPIETARIO UNICO
10476,1.15,5.06,0.0,100.0,5554.56,TERMINADO,COMERCIO,PROPIETARIO UNICO
10477,5.97,15.46,0.0,100.0,13888.99,TERMINADO,COMERCIO,PROPIETARIO UNICO
10478,40.75,45,0.0,100.0,62052.7,TERMINADO,COMERCIO,PROPIETARIO UNICO
10479,65.23,72,0.0,100.0,99310.45,TERMINADO,COMERCIO,PROPIETARIO UNICO

# EDA

In [24]:
data_df.dtypes

AREA_TERRENO             object
AREA_CONSTRUIDA          object
AREA_COMUN              float64
PORCENTAJE_PROPIEDAD    float64
BASE_IMPONIBLE           object
ESTADO_PREDIO            object
USO_PREDIO               object
CONDICION_PROPIEDAD      object
dtype: object

In [25]:
data_df.dtypes.value_counts()

object     6
float64    2
Name: count, dtype: int64

In [26]:
import re

def to_snake_case(name):
    # Insert an underscore before any uppercase letter that is not at the start of the string
    name = re.sub(r'(?<!^)(?=[A-Z])', '', name)
    return name.lower()

data_df.columns = [to_snake_case(col) for col in data_df.columns]

In [27]:
data_df

,area_terreno,area_construida,area_comun,porcentaje_propiedad,base_imponible,estado_predio,uso_predio,condicion_propiedad
0,0.19,7.9,0.0,100.0,"6,067.28",TERMINADO,COMERCIO,PROPIETARIO UNICO
1,68.48,60.04,0.0,100.0,"58,552.60",TERMINADO,COMERCIO,PROPIETARIO UNICO
2,83.7,340.25,0.0,100.0,"195,000.16",TERMINADO,COMERCIO,PROPIETARIO UNICO
3,4.35,20,0.0,100.0,"8,929.20",TERMINADO,COMERCIO,PROPIETARIO UNICO
4,23.9,59.81,0.0,100.0,"27,866.22",TERMINADO,COMERCIO,PROPIETARIO UNICO
...,...,...,...,...,...,...,...,...
10475,44.96,176.93,0.0,100.0,72990.44,TERMINADO,COMERCIO,PROPIETARIO UNICO
10476,1.15,5.06,0.0,100.0,5554.56,TERMINADO,COMERCIO,PROPIETARIO UNICO
10477,5.97,15.46,0.0,100.0,13888.99,TERMINADO,COMERCIO,PROPIETARIO UNICO
10478,40.75,45,0.0,100.0,62052.7,TERMINADO,COMERCIO,PROPIETARIO UNICO
10479,65.23,72,0.0,100.0,99310.45,TERMINADO,COMERCIO,PROPIETARIO UNICO

In [28]:
data_df.isnull().sum()

area_terreno            0
area_construida         0
area_comun              0
porcentaje_propiedad    0
base_imponible          0
estado_predio           0
uso_predio              0
condicion_propiedad     0
dtype: int64

# CONVERSION DE TIPOS DE DATOS

In [29]:
data_df.columns

Index(['area_terreno', 'area_construida', 'area_comun', 'porcentaje_propiedad',
       'base_imponible', 'estado_predio', 'uso_predio', 'condicion_propiedad'],
      dtype='object')

In [30]:
columns_to_convert = ['area_terreno', 'area_construida', 'area_comun', 'porcentaje_propiedad', 'base_imponible']

for col in columns_to_convert:
    if data_df[col].dtype == 'object':
        # Remove commas for 'base_imponible' and strip spaces for all object columns
        if col == 'base_imponible':
            data_df[col] = data_df[col].astype(str).str.replace(',', '', regex=False).str.strip()
        else:
            data_df[col] = data_df[col].astype(str).str.strip()

        # Convert to numeric, coercing errors to NaN
        data_df[col] = pd.to_numeric(data_df[col], errors='coerce')

    # Ensure the column is float64, fill NaN with 0 if created by 'coerce'
    data_df[col] = data_df[col].fillna(0).astype('float64')

print(data_df.dtypes)

area_terreno            float64
area_construida         float64
area_comun              float64
porcentaje_propiedad    float64
base_imponible          float64
estado_predio            object
uso_predio               object
condicion_propiedad      object
dtype: object

/tmp/ipykernel_19986/2815713473.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_df[col] = data_df[col].astype(str).str.strip()
/tmp/ipykernel_19986/2815713473.py:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_df[col] = pd.to_numeric(data_df[col], errors='coerce')
/tmp/ipykernel_19986/2815713473.py:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_df[col] = data_df[col].fillna(0).astype('float64')
/tmp/ipykernel_19986/2815713473.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_df[col] = data_df[col].astype(str).str.strip()
/tmp/ipykernel_19986/2815713473.py:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_df[col] = pd.to_numeric(data_df[col], errors='coerce')
/tmp/ipykernel_19986/2815713473.py:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_df[col] = data_df[col].fillna(0).astype('float64')
/tmp/ipykernel_19986/2815713473.py:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_df[col] = data_df[col].fillna(0).astype('float64')
/tmp/ipykernel_19986/2815713473.py:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_df[col] = data_df[col].fillna(0).astype('float64')
/tmp/ipykernel_19986/2815713473.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_df[col] = data_df[col].astype(str).str.replace(',', '', regex=False).str.strip()
/tmp/ipykernel_19986/2815713473.py:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_df[col] = pd.to_numeric(data_df[col], errors='coerce')
/tmp/ipykernel_19986/2815713473.py:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_df[col] = data_df[col].fillna(0).astype('float64')

In [32]:
data_df.dtypes

area_terreno            float64
area_construida         float64
area_comun              float64
porcentaje_propiedad    float64
base_imponible          float64
estado_predio            object
uso_predio               object
condicion_propiedad      object
dtype: object