# 📊 Tratamiento de Datos Faltantes (Missing Data)

## 🧠 ¿Qué son los datos faltantes?

Los **datos faltantes** (missing values) son valores que no están presentes en un dataset.  
Generalmente se representan como:

- `NaN` (Not a Number)
- `None`
- Celdas vacías

Ejemplo:

| nombre | edad | salario |
|--------|------|--------|
| Ana    | 25   | 2000   |
| Luis   | NaN  | 1800   |
| Marta  | 30   | NaN    |

---

## ⚠️ ¿Por qué ocurren los datos faltantes?

Los datos faltantes pueden aparecer por varias razones:

### 1. Error humano
- No se ingresó información
- Formularios incompletos

### 2. Problemas técnicos
- Fallos en sensores o sistemas
- Errores en la recolección de datos

### 3. Datos no aplicables
- Ejemplo: una persona sin hijos → campo "número de hijos" vacío

### 4. Pérdida de información
- Datos eliminados o corruptos durante procesos ETL

In [1]:
import pandas as pd

# CREAMOS UN DATAFRAME DE PRUEBA

In [2]:
df = pd.DataFrame.from_dict(
    data= {
        "a":list('asdfasdfas'),
        "b":range(0,10)
    }
)
df

   a  b
0  a  0
1  s  1
2  d  2
3  f  3
4  a  4
5  s  5
6  d  6
7  f  7
8  a  8
9  s  9

#GENERAMOS VALORES NULOS

In [3]:
df.iloc[2:5,0] = None
df.iloc[6:7,1] = None
df

      a    b
0     a  0.0
1     s  1.0
2  None  2.0
3  None  3.0
4  None  4.0
5     s  5.0
6     d  NaN
7     f  7.0
8     a  8.0
9     s  9.0

# VERIFICAMOS VALORES NULOS

In [4]:
df.isna()

       a      b
0  False  False
1  False  False
2   True  False
3   True  False
4   True  False
5  False  False
6  False   True
7  False  False
8  False  False
9  False  False

# CONTEO DE NULOS

In [5]:
df.isna().sum()

a    3
b    1
dtype: int64

# CONTEO TOTAL DE NULOS

In [6]:
df.isna().sum().sum()

np.int64(4)

# CONTEO POR CASOS

In [7]:
df.isna().pipe(
    lambda df_1: (
        df_1.sum()
        .reset_index(name='n_missing')
        .rename(columns={'index':'variable'})
        .assign(
            n_cases=len(df_1),
            pct_missing=lambda df_2: df_2.n_missing / df_2.n_cases * 100,
        )
    )
)

  variable  n_missing  n_cases  pct_missing
0        a          3       10         30.0
1        b          1       10         10.0