# RED NEURONAL PARA ENTRENAMIENTO DE CLASIFICACIÓN DE CHURN EN EMPRESA DE TELECOMUNICACIONES

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [4]:
df = pd.read_csv('/content/telco_data_transformed.csv').dropna()
df.head(10)

,gender,partner,dependents,phone_service,paperless_billing,churn,device_protection_no,device_protection_noservice,device_protection_yes,movies_no,...,security_no,security_noservice,security_yes,internet_dsl,internet_fiber,internet_no,senior_citizen,tenure,monthly_charges,total_charges
0,0.0,1.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,...,1.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,29.85,29.85
1,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,1.0,...,0.0,0.0,1.0,1.0,0.0,0.0,0.0,34.0,56.95,1889.50
2,1.0,0.0,0.0,1.0,1.0,1.0,1.0,0.0,0.0,1.0,...,0.0,0.0,1.0,1.0,0.0,0.0,0.0,2.0,53.85,108.15
3,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,...,0.0,0.0,1.0,1.0,0.0,0.0,0.0,45.0,42.30,1840.75
4,0.0,0.0,0.0,1.0,1.0,1.0,1.0,0.0,0.0,1.0,...,1.0,0.0,0.0,0.0,1.0,0.0,0.0,2.0,70.70,151.65
5,0.0,0.0,0.0,1.0,1.0,1.0,0.0,0.0,1.0,0.0,...,1.0,0.0,0.0,0.0,1.0,0.0,0.0,8.0,99.65,820.50
6,1.0,0.0,1.0,1.0,1.0,0.0,1.0,0.0,0.0,1.0,...,1.0,0.0,0.0,0.0,1.0,0.0,0.0,22.0,89.10,1949.40
7,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,...,0.0,0.0,1.0,1.0,0.0,0.0,0.0,10.0,29.75,301.90
8,0.0,1.0,0.0,1.0,1.0,1.0,0.0,0.0,1.0,0.0,...,1.0,0.0,0.0,0.0,1.0,0.0,0.0,28.0,104.80,3046.05
9,1.0,0.0,1.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,...,0.0,0.0,1.0,1.0,0.0,0.0,0.0,62.0,56.15,3487.95

In [5]:
df.isnull().sum().sum()

np.int64(0)

In [6]:
corr_matrix = df.corr()
corr_churn = corr_matrix[['churn']].sort_values(by='churn',ascending=False)
corr_churn

                                churn
churn                        1.000000
contract_month               0.404565
security_no                  0.342235
tech_support_no              0.336877
internet_fiber               0.307463
payment_check                0.301455
backup_no                    0.267595
device_protection_no         0.252056
monthly_charges              0.192858
paperless_billing            0.191454
senior_citizen               0.150541
movies_no                    0.130920
tv_no                        0.128435
tv_yes                       0.063254
movies_yes                   0.060860
multiple_lines_yes           0.040033
phone_service                0.011691
gender                      -0.008545
multiple_lines_noservice    -0.011691
multiple_lines_no           -0.032654
device_protection_yes       -0.066193
backup_yes                  -0.082307
payment_mail                -0.090773
payment_transfer            -0.118136
internet_dsl                -0.124141
payment_creditcard          -0.134687
partner                     -0.149982
dependents                  -0.163128
tech_support_yes            -0.164716
security_yes                -0.171270
contract_year               -0.178225
total_charges               -0.199484
device_protection_noservice -0.227578
security_noservice          -0.227578
tech_support_noservice      -0.227578
movies_noservice            -0.227578
tv__no internet service     -0.227578
internet_no                 -0.227578
backup_noservice            -0.227578
contract_twoyears           -0.301552
tenure                      -0.354049

In [7]:
cols = corr_churn.index.tolist()
cols.remove('churn')
cols

['contract_month',
 'security_no',
 'tech_support_no',
 'internet_fiber',
 'payment_check',
 'backup_no',
 'device_protection_no',
 'monthly_charges',
 'paperless_billing',
 'senior_citizen',
 'movies_no',
 'tv_no',
 'tv_yes',
 'movies_yes',
 'multiple_lines_yes',
 'phone_service',
 'gender',
 'multiple_lines_noservice',
 'multiple_lines_no',
 'device_protection_yes',
 'backup_yes',
 'payment_mail',
 'payment_transfer',
 'internet_dsl',
 'payment_creditcard',
 'partner',
 'dependents',
 'tech_support_yes',
 'security_yes',
 'contract_year',
 'total_charges',
 'device_protection_noservice',
 'security_noservice',
 'tech_support_noservice',
 'movies_noservice',
 'tv__no internet service',
 'internet_no',
 'backup_noservice',
 'contract_twoyears',
 'tenure']

In [8]:
X = df[cols].values
y = df['churn'].values.reshape(-1,1)

# CREAR RED NEURONAL